[package]
name = "skitgubbe-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive", "serde_derive"] }
strum = { version = "0.25.0", features = ["strum_macros"] }
strum_macros = "0.25.3"
tokio = { version = "1.34.0", features = ["full"] }
websocket = "0.27.0"
